Begin to add damonize process and add logs

diff --git a/daemon/nao-elastic-river-rabbitmq b/daemon/nao-elastic-river-rabbitmq
--- a/daemon/nao-elastic-river-rabbitmq
+++ b/daemon/nao-elastic-river-rabbitmq
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! /bin/sh
 ### BEGIN INIT INFO
 # Provides: nao-elastic-river-rabbitmq
 # Required-Start: $local_fs $network
@@ -9,75 +9,160 @@
 # Description: Startup/shutdown script for an ElasticSearch river for RabbitMQ
 ### END INIT INFO
 
-LOG_PATH="%log_path%"
-DAEMON_PATH="%MYPATH%"
-PROG="nao-elastic-river-rabbitmq"
-DAEMON_APP="python"
-SCRIPT="bin/naoRiver.py"
-ARGS=""
-LOCK_FILE="${DAEMON_PATH}/.state.lock"
+# Author: Nicolas Marniesse
+#
+# Please remove the "Author" lines above and replace them
+# with your own name if you copy and modify this script.
 
-start () {
-    echo "Starting $PROG: "
-    if [ ! -f "$LOCK_FILE" ]; then
-        echo "Error, process $PROG is already running. Use 'forcerestart' if needed."
-        return 0
-    fi
-    cd $DAEMON_PATH && $DAEMON_APP $SCRIPT $ARGS &
-        RETVAL=$?
-    echo
-    [ $RETVAL = 0 ] && $LOCK_FILE
-    return $RETVAL
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="ElasticSearch river for RabbitMQ"
+NAME=nao-elastic-river-rabbitmq.sh
+DAEMON=/usr/bin/$NAME
+DAEMON_ARGS="--options args"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+LOCK_FILE="/opt/nao-elastic-river-rabbitmq/.state.lock"
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+VERBOSE="yes"
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+
+	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
 
-stop () {
-    if [ ! -f "$LOCK_FILE" ]; then
-        echo "Process $PROG is not running. Use forcestop if this is incorrect."
-        return 0
-    fi
-    realstop
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+
+	if [ -f "$LOCK_FILE" ]; then
+		rm -rf LOCK_FILE
+		sleep 2
+	fi
+
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
 }
 
-realstop () {
-    echo "Stopping $PROG: "
-    rm -f "$LOCK_FILE" 2> /dev/null
-    return 0
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
 }
 
-restart() {
-    stop
-    start
-}
-
-forcestop () {
-    realstop
-}
-forcerestart() {
-    forcestop
-    start
-}
-
-
-case $1 in
-    start)
-        start
-        ;;
-    stop)
-        stop
-        ;;
-    restart)
-        restart
-        ;;
-    forcerestart)
-        forcerestart
-        ;;
-    forcestop)
-        forcestop
-        ;;
-    *)
-        echo "Usage: $PROG {start|stop|restart|forcestop|forcerestart}"
-        exit 3
-        ;;
+case "$1" in
+  start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
+  *)
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit $RETVAL
+:
