Script install.sh and logs

diff --git a/daemon/nao-elastic-river-rabbitmq b/daemon/nao-elastic-river-rabbitmq
--- a/daemon/nao-elastic-river-rabbitmq
+++ b/daemon/nao-elastic-river-rabbitmq
@@ -25,6 +25,7 @@ DAEMON_ARGS="--options args"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 LOCK_FILE="/opt/nao-elastic-river-rabbitmq/.state.lock"
+USER="%user%"
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -36,11 +37,6 @@ LOCK_FILE="/opt/nao-elastic-river-rabbitmq/.state.lock"
 . /lib/init/vars.sh
 VERBOSE="yes"
 
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
-. /lib/lsb/init-functions
-
 #
 # Function that starts the daemon/service
 #
@@ -50,16 +46,23 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
 
-	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
+	if [ -f $LOCK_FILE ]; then
+        echo "Error, process $PROG is already running. Use 'forcerestart' if needed."
+        return 1
+    fi
 
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+	su -l $USER -s /bin/bash -c "$DAEMON" &
+	sleep 1
+
+	NBR=$(ps -eF | grep $NAME | grep -v grep | wc -l)
+	echo "NBR = $NBR"
+	if [ $NBR = 0 ]; then
+		return 2
+	fi
+	if [ "$NBR" != "0" ]; then
+		return 0
+	fi
 }
 
 #
@@ -73,66 +76,72 @@ do_stop()
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
 
-	if [ -f "$LOCK_FILE" ]; then
-		rm -rf LOCK_FILE
-		sleep 2
+	if [ ! -f "$LOCK_FILE" ]; then
+		return 1
 	fi
 
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
-}
+	rm -f $LOCK_FILE
+	if [ -f "$LOCK_FILE" ]; then
+		return 2
+	fi
+	sleep 2
 
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	# On vérifie que le daemon est bien stoppé
+	NBR=$(ps -eF | grep $NAME | grep -v grep | wc -l)
+	if [ $NBR != 0 ]; then
+		# On essaye de killer par la force
+		pkill $NAME
+		sleep 1
+		NBR=$(ps -eF | grep $NAME | grep -v grep | wc -l)
+		if [ $NBR != 0 ]; then
+			return 2
+		fi
+	fi
+
 	return 0
 }
 
+do_status()
+{
+	# Return
+	#   0 if daemon is working
+	#   1 if daemon is not working
+	NBR=$(ps -eF | grep $NAME | grep -v grep | wc -l)
+	if [ $NBR = 0 ]; then
+		return 1;
+	fi
+	return 0;
+}
+
+
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0|1) [ "$VERBOSE" != no ] && echo "Starting $DESC" "$NAME" && echo "          [OK]" ;;
+		2) [ "$VERBOSE" != no ] && echo "Starting $DESC" "$NAME" && echo "          [Fail]" ;;
 	esac
 	;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0|1) [ "$VERBOSE" != no ] && echo "Stopping $DESC" "$NAME" && echo "          [OK]" ;;
+		2) [ "$VERBOSE" != no ] && echo "Stopping $DESC" "$NAME" && echo "          [Fail]" ;;
 	esac
 	;;
   status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	do_status
+	case "$?" in
+		0) echo "Daemon is working" ;;
+		1) echo "Daemon is not working" ;;
+	esac
 	;;
   #reload|force-reload)
 	#
 	# If do_reload() is not implemented then leave this commented out
 	# and leave 'force-reload' as an alias for 'restart'.
 	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#echo "Reloading $DESC" "$NAME"
 	#do_reload
 	#log_end_msg $?
 	#;;
@@ -141,26 +150,26 @@ case "$1" in
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	echo "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
 	  0|1)
 		do_start
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+			0) echo "          [OK]" ;;
+			1) echo "          [Fail]" ;; # Old process is still running
+			*) echo "          [Fail]" ;; # Failed to start
 		esac
 		;;
 	  *)
 		# Failed to stop
-		log_end_msg 1
+		echo "          [Fail]"
 		;;
 	esac
 	;;
   *)
 	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
 	exit 3
 	;;
 esac
